name: RestyGWT
markdown: redcarpet
pygments: true
release_base: http://repo.fusesource.com/nexus/content/groups/public/org/fusesource/restygwt/restygwt
project_name: restygwt
project_id: resty-gwt
project_snapshot_version: 2.0.3-SNAPSHOT
project_version: 2.0.2
project_versions: [1.0,1.1,1.2,1.3,1.4,2.0.1,2.0.2]
git_user_url: git://github.com/chirino/resty-gwt.git
github_page: https://github.com/resty-gwt/
issue_tracker: https://github.com/resty-gwt/resty-gwt/issues
old_url: http://restygwt.fusesource.org/
